### PR TITLE
Update CodeEditorField.ss and Readme

### PR DESCRIPTION
**Pull request by derralf**
prevent '<script>'-tags from breaking the cms (e.g. SiteConfig/Settings not loading anymore)

### CODE REVIEW

**Comment by jinjie** [comment]
> prevent '<script>'-tags from breaking the cms (e.g. SiteConfig/Settings not loading anymore)

Hi @derralf . May I ask what is the issue you're facing that initiate this PR? Can you provide the steps to reproduce the error?

**Comment by derralf** [comment]
Hi @jinjie,

**CodeEditorField.ss**

I'm using this field type in a SiteConfigExtension to edit the Google Analytics Code for the Site.
CMS Version is 4.3.3.
PHP 7.2.1 with MAMP on a local machine.

Issue:
As soon as I place a `<script></script>`-Tag in the field + save + reload -> the CMS-Page (Backend) will not load again.
(seems as if it loads forever... ?flush or browser-reload won't help)

If I change from `CodeEditorField` to `TextareaField` the CMS-Page will work/load again.
(when changing back to `CodeEditorField` it again refuses to load).

Changing the variable in the Template from `{$Value.RAW}` to `{$Value}` makes the Error goe away...


**README**

this is just  a little update to explain how to set the "mode" for ACE

**Comment by jinjie** [comment]
@derralf 

SS4's [TextareaField](https://github.com/silverstripe/silverstripe-framework/blob/4/templates/SilverStripe/Forms/TextareaField.ss) template uses `$ValueEntities.RAW`

Does that work instead of `$Value.RAW`?

**Comment by derralf** [comment]
@jinjie 
YES, works fine with `{$ValueEntities.RAW}`

**Comment by jinjie** [comment]
Thanks @derralf

**Pull request merged**
